---
title: "supporting_file"
author: "Gabe Cederberg"
date: "2/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Loading the important packages.

library(tidyverse)
library(readr)
library(janitor)
library(ggthemes)
library(viridis)  
library(tidycensus)
library(transformr)
library(lubridate)
library(RColorBrewer)
library(scales)
library(tmaptools)
library(patchwork)
library(RCurl)
library(readxl)
library(zoo)

# Turn off scientific notation

options(scipen = 999)

# Cache shapefiles for use in future sessions

options(tigris_use_cache = TRUE)

```

```{r}
end_date <- "2021-02-11"
theme2 <- theme(plot.title = element_blank(),
        legend.title = element_blank(),
        legend.text = element_blank(),
        legend.position = "right",
        legend.key.width = unit(0.5, "cm"))
```


```{r}
# Case and death data

state_text <- getURL("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")
state <- read_csv(state_text) %>% 
  group_by(state) %>% 
  mutate(new_cases = cases - lag(cases, k = 1)) %>% 
  mutate(new_cases = case_when(new_cases < 0 ~ 0,
                               new_cases >= 0 ~ new_cases)) %>% 
  mutate(cases_7day_avg =  rollapply(new_cases, 7, mean, fill = NA, align = 'right')) %>% 
  mutate(delta_cases_WoW = 100 * (0 - (1 - (cases_7day_avg / lag(cases_7day_avg, 7, default = 0, order_by = date))))) %>% 
  
  mutate(new_deaths = deaths - lag(deaths, k = 1)) %>% 
  mutate(new_deaths = case_when(new_deaths < 0 ~ 0,
                               new_deaths >= 0 ~ new_deaths)) %>% 
  mutate(deaths_7day_avg =  rollapply(new_deaths, 7, mean, fill = NA, align = 'right')) %>% 
  mutate(delta_deaths_WoW = 100 * (0 - (1 - (deaths_7day_avg / lag(deaths_7day_avg, 7, default = 0, order_by = date))))) %>% 
  slice_max(order_by = date, n = 1) %>% 
  select(date,
         state, 
         cases_7day_avg,
         delta_cases_WoW,
         "cumulative_cases" = cases,
         deaths_7day_avg,
         delta_deaths_WoW,
         "cumulative_deaths" = deaths)

# State geography and population

state_pop <- get_acs(geography = "state",
                  variables = c(pop = "B01003_001"), 
                  year = 2018,
                  geometry = TRUE,
                  shift_geo = TRUE) %>% 
  clean_names() %>% 
   select(geoid, 
          state_name = name, 
        #  "pop" = estimate,
          "state_geometry" = geometry)  

# State abbreviations

# c <- read_excel("data/state_abbreviations.xlsx")

# Vaccines data

vaccines_text <- getURL("https://raw.githubusercontent.com/youyanggu/covid19-cdc-vaccination-data/main/aggregated_adjusted.csv")
vaccines <- read_csv(vaccines_text) %>% 
  clean_names() %>% 
  select(date, 
         "pop" = census2019,
         "state" = long_name,
         "total_doses_administered" = doses_administered,
         "seven_day_avg_doses_adm" = doses_administered_daily_7day_avg,
         "daily_doses_administered" = doses_distributed_daily) %>% 
  filter(!(state %in% c("American Samoa",
                        "Bureau of Prisons",
                        "Dept of Defense",
                        "Federated States of Micronesia",
                        "Guam",
                        "Indian Health Svc",
                        "Long Term Care",
                        "Marshall Islands",
                        "Northern Mariana Islands",
                        "Puerto Rico",
                        "Republic of Palau",
                        "Veterans Health",
                        "Virgin Islands",
                        "United States"))) %>% 
  group_by(state) %>% 
  mutate(delta_vaccines_WoW = 100 * (0 - (1 - (seven_day_avg_doses_adm / 
                                                 lag(seven_day_avg_doses_adm, 7, default = 0, order_by = date))))) %>% 
  slice_max(order_by = date, n = 1) %>% 
  mutate(state = case_when(state == "New York State" ~ "New York",
                           state != "New York State" ~ state))

```

```{r}
a <- vaccines %>% 
  left_join(state, by = "state") 

a$total_doses_administered



b <- state_pop %>% 
  right_join(a, by = c("state_name" = "state"))

```

```{r}

saveRDS(b, file = paste("data_files/map_data", end_date, ".rds", sep = ""))

```





```{r}
vaccines %>% 
  summarize(totalpop = sum(pop),
            totaldoses = sum(total_doses_administered))
```
